<a href="https://colab.research.google.com/github/TheR3dWizard/Innovation-Practices/blob/main/BayesianRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Preprocessing

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder,OneHotEncoder
import pandas as pd
from google.colab import drive

drive.mount('/content/drive')

file_path = "/content/drive/MyDrive/Hypothyroid/hypothyroid.csv"
df = pd.read_csv(file_path)
pd.set_option('display.max_columns', None)
print(df.head())

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
  age sex on thyroxine query on thyroxine on antithyroid medication sick  \
0  41   F            f                  f                         f    f
1  23   F            f                  f                         f    f
2  46   M            f                  f                         f    f
3  70   F            t                  f                         f    f
4  70   F            f                  f                         f    f

  pregnant thyroid surgery I131 treatment query hypothyroid  \
0        f               f              f                 f
1        f               f              f                 f
2        f               f              f                 f
3        f               f              f                 f
4        f               f              f                 f

  query hyperthyroid lithium goitre tumor hypopituitary psych TSH measured  \
0                  f       f      f     f             f     f            t
1                  f       f      f     f             f     f            t
2                  f       f      f     f             f     f            t
3                  f       f      f     f             f     f            t
4                  f       f      f     f             f     f            t

    TSH T3 measured   T3 TT4 measured  TT4 T4U measured   T4U FTI measured  \
0   1.3           t  2.5            t  125            t  1.14            t
1   4.1           t    2            t  102            f     ?            f
2  0.98           f    ?            t  109            t  0.91            t
3  0.16           t  1.9            t  175            f     ?            f
4  0.72           t  1.2            t   61            t  0.87            t

   FTI TBG measured TBG referral source binaryClass
0  109            f   ?            SVHC           P
1    ?            f   ?           other           P
2  120            f   ?           other           P
3    ?            f   ?           other           P
4   70            f   ?             SVI           P

In [ ]:
columns_to_replace = [
    "on thyroxine", "query on thyroxine", "on antithyroid medication",
    "sick", "pregnant", "thyroid surgery", "I131 treatment", "query hypothyroid",
    "TT4 measured", "T4U measured", "FTI measured", "TBG measured",
    "query hyperthyroid", "lithium", "goitre", "tumor",
    "hypopituitary", "psych", "TSH measured", "T3 M","T3 measured"
]
existing_columns = [col for col in columns_to_replace if col in df.columns]
df[existing_columns] = df[existing_columns].replace({'t': 1, 'f': 0}).infer_objects(copy=False)


df.head()

<ipython-input-6-467c88f4df51>:9: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[existing_columns] = df[existing_columns].replace({'t': 1, 'f': 0}).infer_objects(copy=False)

,age,sex,on thyroxine,query on thyroxine,on antithyroid medication,sick,pregnant,thyroid surgery,I131 treatment,query hypothyroid,query hyperthyroid,lithium,goitre,tumor,hypopituitary,psych,TSH measured,TSH,T3 measured,T3,TT4 measured,TT4,T4U measured,T4U,FTI measured,FTI,TBG measured,TBG,referral source,binaryClass
0,41,F,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1.3,1,2.5,1,125,1,1.14,1,109,0,?,SVHC,P
1,23,F,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,4.1,1,2,1,102,0,?,0,?,0,?,other,P
2,46,M,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0.98,0,?,1,109,1,0.91,1,120,0,?,other,P
3,70,F,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0.16,1,1.9,1,175,0,?,0,?,0,?,other,P
4,70,F,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0.72,1,1.2,1,61,1,0.87,1,70,0,?,SVI,P

In [ ]:
df["sex"] = df["sex"].replace({'F': 0, 'M': 1})
df["binaryClass"] = df["binaryClass"].replace({'P': 0, 'N': 1})
df.head()

<ipython-input-7-88a86bf32d42>:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["binaryClass"] = df["binaryClass"].replace({'P': 0, 'N': 1})

,age,sex,on thyroxine,query on thyroxine,on antithyroid medication,sick,pregnant,thyroid surgery,I131 treatment,query hypothyroid,query hyperthyroid,lithium,goitre,tumor,hypopituitary,psych,TSH measured,TSH,T3 measured,T3,TT4 measured,TT4,T4U measured,T4U,FTI measured,FTI,TBG measured,TBG,referral source,binaryClass
0,41,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1.3,1,2.5,1,125,1,1.14,1,109,0,?,SVHC,0
1,23,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,4.1,1,2,1,102,0,?,0,?,0,?,other,0
2,46,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0.98,0,?,1,109,1,0.91,1,120,0,?,other,0
3,70,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0.16,1,1.9,1,175,0,?,0,?,0,?,other,0
4,70,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0.72,1,1.2,1,61,1,0.87,1,70,0,?,SVI,0

In [ ]:
unique_values = df["referral source"].unique()
print(unique_values)

['SVHC' 'other' 'SVI' 'STMW' 'SVHD']

In [ ]:
encoder = OneHotEncoder(sparse_output=False, drop=None)
encoded = encoder.fit_transform(df[['referral source']])

df_encoded = pd.DataFrame(encoded, columns=encoder.get_feature_names_out(['referral source']))
df_encoded = df_encoded.astype(int)

df = df.drop(columns=['referral source']).join(df_encoded)

df.head()

,age,sex,on thyroxine,query on thyroxine,on antithyroid medication,sick,pregnant,thyroid surgery,I131 treatment,query hypothyroid,query hyperthyroid,lithium,goitre,tumor,hypopituitary,psych,TSH measured,TSH,T3 measured,T3,TT4 measured,TT4,T4U measured,T4U,FTI measured,FTI,TBG measured,TBG,binaryClass,referral source_STMW,referral source_SVHC,referral source_SVHD,referral source_SVI,referral source_other
0,41,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1.3,1,2.5,1,125,1,1.14,1,109,0,?,0,0,1,0,0,0
1,23,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,4.1,1,2,1,102,0,?,0,?,0,?,0,0,0,0,0,1
2,46,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0.98,0,?,1,109,1,0.91,1,120,0,?,0,0,0,0,0,1
3,70,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0.16,1,1.9,1,175,0,?,0,?,0,?,0,0,0,0,0,1
4,70,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0.72,1,1.2,1,61,1,0.87,1,70,0,?,0,0,0,0,1,0

In [ ]:
df.replace("?", np.nan, inplace=True)
print(df.isnull().sum())

age                             1
sex                           150
on thyroxine                    0
query on thyroxine              0
on antithyroid medication       0
sick                            0
pregnant                        0
thyroid surgery                 0
I131 treatment                  0
query hypothyroid               0
query hyperthyroid              0
lithium                         0
goitre                          0
tumor                           0
hypopituitary                   0
psych                           0
TSH measured                    0
TSH                           369
T3 measured                     0
T3                            769
TT4 measured                    0
TT4                           231
T4U measured                    0
T4U                           387
FTI measured                    0
FTI                           385
TBG measured                    0
TBG                          3772
binaryClass                     0
referral source_STMW            0
referral source_SVHC            0
referral source_SVHD            0
referral source_SVI             0
referral source_other           0
dtype: int64

<ipython-input-10-dade5bb61dac>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace("?", np.nan, inplace=True)

In [ ]:
from sklearn.impute import SimpleImputer
age_imputer = SimpleImputer(strategy="mean")
sex_imputer = SimpleImputer(strategy="most_frequent")

df["age"] = age_imputer.fit_transform(df[["age"]])
df["sex"] = sex_imputer.fit_transform(df[["sex"]])
df["sex"] = df["sex"].astype(int)
df["age"] = df["age"].astype(int)

df.head()

,age,sex,on thyroxine,query on thyroxine,on antithyroid medication,sick,pregnant,thyroid surgery,I131 treatment,query hypothyroid,query hyperthyroid,lithium,goitre,tumor,hypopituitary,psych,TSH measured,TSH,T3 measured,T3,TT4 measured,TT4,T4U measured,T4U,FTI measured,FTI,TBG measured,TBG,binaryClass,referral source_STMW,referral source_SVHC,referral source_SVHD,referral source_SVI,referral source_other
0,41,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1.3,1,2.5,1,125,1,1.14,1,109,0,NaN,0,0,1,0,0,0
1,23,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,4.1,1,2,1,102,0,NaN,0,NaN,0,NaN,0,0,0,0,0,1
2,46,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0.98,0,NaN,1,109,1,0.91,1,120,0,NaN,0,0,0,0,0,1
3,70,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0.16,1,1.9,1,175,0,NaN,0,NaN,0,NaN,0,0,0,0,0,1
4,70,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0.72,1,1.2,1,61,1,0.87,1,70,0,NaN,0,0,0,0,1,0

In [ ]:
df[["TSH", "T3", "TT4", "T4U", "FTI"]] = df[["TSH", "T3", "TT4", "T4U", "FTI"]].apply(pd.to_numeric, errors='coerce')
df[["TSH", "T3", "TT4", "T4U", "FTI"]] = df[["TSH", "T3", "TT4", "T4U", "FTI"]].fillna(df[["TSH", "T3", "TT4", "T4U", "FTI"]].mean())
print(df[["TSH", "T3", "TT4", "T4U", "FTI"]].isnull().sum())
print(df.columns)

TSH    0
T3     0
TT4    0
T4U    0
FTI    0
dtype: int64
Index(['age', 'sex', 'on thyroxine', 'query on thyroxine',
       'on antithyroid medication', 'sick', 'pregnant', 'thyroid surgery',
       'I131 treatment', 'query hypothyroid', 'query hyperthyroid', 'lithium',
       'goitre', 'tumor', 'hypopituitary', 'psych', 'TSH measured', 'TSH',
       'T3 measured', 'T3', 'TT4 measured', 'TT4', 'T4U measured', 'T4U',
       'FTI measured', 'FTI', 'TBG measured', 'TBG', 'binaryClass',
       'referral source_STMW', 'referral source_SVHC', 'referral source_SVHD',
       'referral source_SVI', 'referral source_other'],
      dtype='object')

In [ ]:
unique_values = df["TBG measured"].unique()
print(unique_values)

[0]

In [ ]:
columns_to_drop = ["TBG", "TBG measured"]
existing_columns = [col for col in columns_to_drop if col in df.columns]

if existing_columns:  # Only drop if they exist
    df = df.drop(columns=existing_columns)
else:
    print("Columns already dropped or not found.")

df.head()

,age,sex,on thyroxine,query on thyroxine,on antithyroid medication,sick,pregnant,thyroid surgery,I131 treatment,query hypothyroid,query hyperthyroid,lithium,goitre,tumor,hypopituitary,psych,TSH measured,TSH,T3 measured,T3,TT4 measured,TT4,T4U measured,T4U,FTI measured,FTI,binaryClass,referral source_STMW,referral source_SVHC,referral source_SVHD,referral source_SVI,referral source_other
0,41,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1.30,1,2.5000,1,125.0,1,1.140,1,109.000000,0,0,1,0,0,0
1,23,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,4.10,1,2.0000,1,102.0,0,0.995,0,110.469649,0,0,0,0,0,1
2,46,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0.98,0,2.0135,1,109.0,1,0.910,1,120.000000,0,0,0,0,0,1
3,70,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0.16,1,1.9000,1,175.0,0,0.995,0,110.469649,0,0,0,0,0,1
4,70,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0.72,1,1.2000,1,61.0,1,0.870,1,70.000000,0,0,0,0,1,0

In [ ]:
print(df.isnull().sum())

age                          0
sex                          0
on thyroxine                 0
query on thyroxine           0
on antithyroid medication    0
sick                         0
pregnant                     0
thyroid surgery              0
I131 treatment               0
query hypothyroid            0
query hyperthyroid           0
lithium                      0
goitre                       0
tumor                        0
hypopituitary                0
psych                        0
TSH measured                 0
TSH                          0
T3 measured                  0
T3                           0
TT4 measured                 0
TT4                          0
T4U measured                 0
T4U                          0
FTI measured                 0
FTI                          0
binaryClass                  0
referral source_STMW         0
referral source_SVHC         0
referral source_SVHD         0
referral source_SVI          0
referral source_other        0
dtype: int64

In [ ]:
#Final Columns

print(df.columns)

Index(['age', 'sex', 'on thyroxine', 'query on thyroxine',
       'on antithyroid medication', 'sick', 'pregnant', 'thyroid surgery',
       'I131 treatment', 'query hypothyroid', 'query hyperthyroid', 'lithium',
       'goitre', 'tumor', 'hypopituitary', 'psych', 'TSH measured', 'TSH',
       'T3 measured', 'T3', 'TT4 measured', 'TT4', 'T4U measured', 'T4U',
       'FTI measured', 'FTI', 'binaryClass', 'referral source_STMW',
       'referral source_SVHC', 'referral source_SVHD', 'referral source_SVI',
       'referral source_other'],
      dtype='object')

# Feature Selection

## 1. Recursive Feature Elimination

In [ ]:
from sklearn.svm import SVC
from sklearn.feature_selection import RFE
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
X = df.drop(columns=["binaryClass"])  # Independent variables
y = df["binaryClass"]  # Dependent variable

In [ ]:
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.40, random_state=42, stratify=y)

X_test, X_val, y_test, y_val = train_test_split(X_temp, y_temp, test_size=0.50, random_state=42, stratify=y_temp)

print(f"Training Set: {X_train.shape}, Testing Set: {X_test.shape}, Validation Set: {X_val.shape}")

Training Set: (2263, 31), Testing Set: (754, 31), Validation Set: (755, 31)

In [ ]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_val = scaler.transform(X_val)

In [ ]:
svm = SVC(kernel="linear")
rfe = RFE(estimator=svm, n_features_to_select=15)

rfe.fit(X_train, y_train)

selected_features = X.columns[rfe.support_]
print("Selected Features:", selected_features)

Selected Features: Index(['age', 'sex', 'on thyroxine', 'thyroid surgery', 'I131 treatment',
       'query hypothyroid', 'query hyperthyroid', 'tumor', 'TSH measured',
       'TSH', 'T3', 'TT4 measured', 'TT4', 'T4U', 'referral source_SVI'],
      dtype='object')

In [ ]:
X_train_selected = rfe.transform(X_train)
X_test_selected = rfe.transform(X_test)
X_val_selected = rfe.transform(X_val)

In [ ]:
# Train SVM model on selected features
svm.fit(X_train_selected, y_train)

# Evaluate accuracy
train_acc = svm.score(X_train_selected, y_train)
test_acc = svm.score(X_test_selected, y_test)
val_acc = svm.score(X_val_selected, y_val)

print(f"Training Accuracy: {train_acc:.2f}")
print(f"Testing Accuracy: {test_acc:.2f}")
print(f"Validation Accuracy: {val_acc:.2f}")

Training Accuracy: 0.97
Testing Accuracy: 0.98
Validation Accuracy: 0.97

# Training With Models

## Bayesian Ridge Regression

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import BayesianRidge
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score,f1_score




selected_features = ['age', 'on thyroxine', 'thyroid surgery', 'query hypothyroid', 'tumor', 'TSH measured', 'TSH', 'T3', 'TT4 measured', 'TT4']
target_column = "binaryClass"

X = df[selected_features]
y = df[target_column]


if y.dtype == 'object':
    y = pd.factorize(y)[0]


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


model = BayesianRidge()
model.fit(X_train, y_train)


y_pred = model.predict(X_test)


y_pred_class = np.round(y_pred).astype(int)


accuracy = accuracy_score(y_test, y_pred_class) * 100

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
f1 = f1_score(y_test,y_pred_class,average="weighted")

print(f"Mean Squared Error: {mse:.4f}")
print(f"R² Score: {r2:.4f}")
print(f"F1 Score: {f1:.4f}")

print(f"Accuracy for first 15 features: {accuracy:.2f}%")

Mean Squared Error: 0.0534
R² Score: 0.2474
F1 Score: 0.9078
Accuracy for first 15 features: 93.25%

## Artificial Neural Network

In [ ]:
#Pre processing

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler




selected_features = ['age', 'sex', 'on thyroxine', 'query on thyroxine',
       'on antithyroid medication', 'sick', 'pregnant', 'thyroid surgery',
       'I131 treatment', 'query hypothyroid', 'query hyperthyroid', 'lithium',
       'goitre', 'tumor', 'hypopituitary', 'psych', 'TSH measured', 'TSH',
       'T3 measured', 'T3', 'TT4 measured', 'TT4', 'T4U measured', 'T4U',
       'FTI measured', 'FTI', 'binaryClass', 'referral source_STMW',
       'referral source_SVHC', 'referral source_SVHD', 'referral source_SVI',
       'referral source_other']
target_column = "binaryClass"

X = df[selected_features]
y = df[target_column]


if y.dtype == 'object':
    y = pd.factorize(y)[0]


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
#building the actual model
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(16,activation="relu"),
    Dense(1, activation='sigmoid')
])

model.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])
history = model.fit(X_train,y_train,epochs=10,batch_size=32,validation_data=(X_test,y_test))

Epoch 1/10

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

95/95 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.7277 - loss: 0.4842 - val_accuracy: 0.9868 - val_loss: 0.0613
Epoch 2/10
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9910 - loss: 0.0427 - val_accuracy: 0.9987 - val_loss: 0.0105
Epoch 3/10
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0064 - val_accuracy: 0.9987 - val_loss: 0.0049
Epoch 4/10
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0022 - val_accuracy: 0.9987 - val_loss: 0.0035
Epoch 5/10
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 0.0011 - val_accuracy: 0.9987 - val_loss: 0.0028
Epoch 6/10
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 6.9491e-04 - val_accuracy: 0.9987 - val_loss: 0.0025
Epoch 7/10
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 5.2677e-04 - val_accuracy: 0.9987 - val_loss: 0.0023
Epoch 8/10
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 3.3410e-04 - val_accuracy: 0.9987 - val_loss: 0.0022
Epoch 9/10
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 2.3140e-04 - val_accuracy: 0.9987 - val_loss: 0.0019
Epoch 10/10
95/95 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 1.0000 - loss: 2.0718e-04 - val_accuracy: 0.9987 - val_loss: 0.0018

In [ ]:
from sklearn.metrics import f1_score

loss, accuracy = model.evaluate(X_test,y_test)
print(f"Test Loss: {loss:.4f}")
print(f"Test Accuracy: {accuracy:.4f}")


pred = model.predict(X_test)
pred = np.round(pred).astype(int)

f1 = f1_score(y_test,pred,average="weighted")
print(f"F1 Score: {f1:.4f}")

24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9991 - loss: 0.0013
Test Loss: 0.0018
Test Accuracy: 0.9987
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
F1 Score: 0.9987